pipeline{

    agent any

    stages{
        stage('Deploy') {

            steps {

                sh '''

                oc project oqrvvr-deploy-strategies

                oc start-build greeting-service --follow --wait

                '''

            }

        }

    }

}