pipeline{

    agent any

    stages{
        stage('Deploy') {

            steps {

                sh '''

                oc project moyuqh-greetings

                oc start-build greeting-service --follow --wait

                '''

            }

        }

    }

}